### ISSUE TITLE
Aspect Ratio

### ISSUE THREAD

**Issue by dreifachtier** [pranjaldatta/DenseDepth-Pytorch#1]
Hello pranjaldatta, thank you for publishing your code! In the examples/ folder the aspect ratios of the calculated depth image and the source image do not match. I haven't found out how to solve this yet, the neural net seems to get tensors of the shape [1, 3, 320,240] instead of [1,3,240,320]

**Comment by pranjaldatta** [comment]
Hey @dreifachtier! 

1. For the test.py script, where the examples/ images are used, [load_images](https://github.com/pranjaldatta/DenseDepth-Pytorch/blob/0ab262574448aab347cfcde3086ae09a207a2ad6/densedepth/utils.py#L87) function is used to ensure all input images are of the same dimensions.

2. For the train.py, the training images in the NYUv2 dataset are by default [640, 480, 3] and the depth maps are resized [here](https://github.com/pranjaldatta/DenseDepth-Pytorch/blob/0ab262574448aab347cfcde3086ae09a207a2ad6/densedepth/data.py#L101).

Hope I was able to clarify! Happy to help if things are still unclear.

**Comment by dreifachtier** [comment]
Hello pranjaldatta,

thank you very much for your response! I didn't see the resizing in the "load_images" function. After changing  the .resize((480, 640)) expresssion to .resize((640, 480)) in the "load_images" code, the program works as expected. Maybe this is a slight error in the implementation, since the resize-operation of PIL expects the argument tuple in the form (width, height) = (640, 480) and not (height, width) = (480,640) as it is currently implemented. Maybe you could check this in your code. Thanks again for your help!

**Comment by pranjaldatta** [comment]
Hey @dreifachtier!
 
Thanks for pointing the error out. That was indeed a stupid mistake. It's been fixed in the latest commit. 

Thanks!
