### ISSUE TITLE
Dataset download link is invalid and the script does not work

### ISSUE THREAD

**Issue by Nyte-BK201** [pranjaldatta/DenseDepth-Pytorch#2]
The command
`python DenseDepth-Pytorch/densedepth/download_data.py`
fails due to the link inside python script is invalid. Is there any fix of the link?

**Comment by pranjaldatta** [comment]
Hey @Nyte-BK201, thanks for pointing out the stale link. It has been fixed. Let me know, if it resolves your issue.

**Comment by Nyte-BK201** [comment]
> Hey @Nyte-BK201, thanks for pointing out the stale link. It has been fixed. Let me know, if it resolves your issue.

Thanks so much for your quick fix! It works now, hope you a nice day.
