### ISSUE TITLE
Trained model

### ISSUE THREAD

**Issue by bricksaver** [pranjaldatta/DenseDepth-Pytorch#4]
Is there a pretrained model that is downloadable?

**Comment by pranjaldatta** [comment]
Hey @bricksaver, the training module automatically downloads the pre-trained model from a google-drive. You can find more about this [here](https://github.com/pranjaldatta/DenseDepth-Pytorch/blob/820fabe83e32f7fceebfadfc373af43118241f54/densedepth/download_data.py#L5). You can manually download the weights at [here](https://drive.google.com/uc?id=1fdFu5NGXe4rTLYKD5wOqk9dl-eJOefXo).

If the auto-download, fails let me know.

**Comment by bricksaver** [comment]
I downloaded the data from the link you provided and it downloads nyu_depth.zip. Isn't that the NYU data used in train.py to train the model though?
Is the model in the zip file?

**Comment by pranjaldatta** [comment]
Hey @bricksaver, I had a closer look and it seems like there has been a link mismatch, or the weight file must have been deleted from google drive. I am working to fix the problem. Really sorry for the error.

**Comment by bricksaver** [comment]
No worries. I finished training the model so I have the model regardless :)
