### ISSUE TITLE
How often should checkpoint be saving?

### ISSUE THREAD

**Issue by bricksaver** [pranjaldatta/DenseDepth-Pytorch#5]
Looking at the 'train.py' code, it seems the model should be saving checkpoints during training every epoch. Is that right?

Wondering since my model hasn't been saving any checkpoints.

**Comment by pranjaldatta** [comment]
Yes that seems to be accurate behavior. Can you mention what arguments you are passing into `train.py` ?

**Comment by bricksaver** [comment]
Thanks for the response! It was my mistake. Actually, it was saving checkpoints, it just wasn't showing in my file explorer, but was visible in my terminal.
