### ISSUE TITLE
How to get grayscale output colormap?

### ISSUE THREAD

**Issue by bricksaver** [pranjaldatta/DenseDepth-Pytorch#7]
Hi! Do you know how I can convert the reddish/pinkish output depth map to grayscale?

**Comment by pranjaldatta** [comment]
> Hi! Do you know how I can convert the reddish/pinkish output depth map to grayscale?

Hey, so after some quick digging in, I realised you can get a grayscale map if you change the [cmap](https://github.com/pranjaldatta/DenseDepth-Pytorch/blob/820fabe83e32f7fceebfadfc373af43118241f54/densedepth/utils.py#L28) parameter here, from `plasma` to `binary`. The result in one of the images are as following, 

![267_image_result](https://user-images.githubusercontent.com/42492630/123508445-2ab26800-d68d-11eb-9bf6-269ed494c3f4.png)
![308_image_result](https://user-images.githubusercontent.com/42492630/123508447-2be39500-d68d-11eb-9c00-4b3896521855.png)
![312_image_result](https://user-images.githubusercontent.com/42492630/123508448-2c7c2b80-d68d-11eb-9831-55f94ee25a1c.png)


Hope it helps. I will be pushing a commit later today which allows the user to change cmaps from the command line itself, just for convenience.

**Comment by bricksaver** [comment]
I see thanks for the help!
